/** Homepage / comparison showcase entries for non-loan marketplaces */
export const MARKETPLACE_SHOWCASE_PRODUCTS = [
  {
    slug: 'insurance',
    apiKey: 'insurance',
    kind: 'marketplace',
    route: '/(customer)/insurance',
    label: 'Insurance',
    shortLabel: 'Insurance',
    icon: 'Shield',
    description: 'Compare life, health, motor, and travel insurance from trusted insurers.',
    interestRange: 'From ₹500/month',
    features: ['Life & health plans', 'Motor insurance', 'Tax benefits (80C/80D)', 'Quick policy quotes'],
    color: '#059669',
    visibilityKey: 'insuranceMarketplace',
  },
  {
    slug: 'mutual_fund',
    apiKey: 'mutual_funds',
    kind: 'marketplace',
    route: '/(customer)/mutual-funds',
    label: 'Mutual Fund',
    shortLabel: 'Mutual Fund',
    icon: 'TrendingUp',
    description: 'Discover SIP and lump-sum mutual fund options matched to your goals.',
    interestRange: 'SIP from ₹500/month',
    features: ['Equity & debt funds', 'SIP from ₹500', 'Goal-based investing', 'Top-rated AMCs'],
    color: '#d97706',
    visibilityKey: 'mutualFundMarketplace',
  },
  {
    slug: 'post_office',
    apiKey: 'post_office',
    kind: 'marketplace',
    route: '/(customer)/post-office',
    label: 'Post Office',
    shortLabel: 'Post Office',
    icon: 'Mail',
    description: 'Compare PPF, NSC, KVP, SCSS, MIS and other India Post savings schemes.',
    interestRange: 'Govt-backed returns',
    features: ['PPF & Sukanya Samriddhi', 'NSC & KVP', 'SCSS for seniors', 'Built-in calculator'],
    color: '#dc2626',
    visibilityKey: 'postOfficeMarketplace',
  },
  {
    slug: 'government_schemes',
    apiKey: 'government_schemes',
    kind: 'marketplace',
    route: '/(customer)/government-schemes',
    label: 'Government Schemes',
    shortLabel: 'Govt Schemes',
    icon: 'Landmark',
    description: 'Explore central and state schemes for loans, subsidies, pensions, and insurance.',
    interestRange: 'Subsidies & low rates',
    features: ['PM Mudra & PMEGP', 'NPS & pensions', 'PMJJBY & PMSBY', 'Solar & MSME subsidies'],
    color: '#1d4ed8',
    visibilityKey: 'governmentSchemesMarketplace',
  },
  {
    slug: 'investment',
    apiKey: 'investment',
    kind: 'marketplace',
    route: '/(customer)/investment-marketplace',
    label: 'Investment',
    shortLabel: 'Investment',
    icon: 'Gem',
    description: 'Compare sovereign gold bonds, ETFs, bonds, REITs, and InvITs.',
    interestRange: 'Diversified assets',
    features: ['Sovereign gold bonds', 'Gold & silver ETFs', 'Corporate bonds', 'REITs & InvITs'],
    color: '#7c3aed',
    visibilityKey: 'investmentMarketplace',
  },
];

export const COMPARE_SHOWCASE_PRODUCT = {
  slug: 'compare_products',
  kind: 'compare',
  route: '/(customer)/product-comparison',
  label: 'Compare Products',
  shortLabel: 'Compare',
  icon: 'GitCompare',
  description: 'Compare loans, credit cards, insurance, and mutual funds side by side.',
  interestRange: 'All categories',
  features: ['Up to 3 products', 'Bank offer comparison', 'Insurance & MF plans', 'One-click apply'],
  color: '#6366f1',
};
